version: '3'

services:
  rtmp-server:
    image: alqutami/rtmp-hls
    ports:
      - "1935:1935"   # RTMP port
      - "8080:8080"   # HLS port
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf